db_name: wordpress_db                             # RDS MySQL database name
db_user: nasdaqwordpressdbadmin                   # RDS MySQL username
db_password: nasdaq-wordpress-db-password         # RDS MySQL password