---
- hosts: wordpress
  become: true
  vars:
    db_name: wordpress_db                             # RDS MySQL database name
    db_user: nasdaqwordpressdbadmin                   # RDS MySQL username
    db_password: nasdaq-wordpress-db-password         # RDS MySQL password
    db_host: your-rds-endpoint                        # RDS MySQL endpoint
  tasks:
    - name: Install required packages
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - wget
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set ownership permissions for WordPress
      command: chown -R apache:apache /var/www/html

    - name: Create wp-config.php
      copy:
        dest: /var/www/html/wp-config.php
        content: |
          <?php
          define( 'DB_NAME', '{{ db_name }}' );
          define( 'DB_USER', '{{ db_user }}' );
          define( 'DB_PASSWORD', '{{ db_password }}' );
          define( 'DB_HOST', '{{ db_host }}' );
          define( 'DB_CHARSET', 'utf8' );
          define( 'DB_COLLATE', '' );
          $table_prefix = 'wp_';
          define( 'WP_DEBUG', false );
          if ( !defined( 'ABSPATH' ) ) {
            define( 'ABSPATH', dirname( __FILE__ ) . '/' );
          }
          require_once ABSPATH . 'wp-settings.php';

    - name: Allow HTTP traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Reload firewall to apply changes
      command: firewall-cmd --reload